name: Run Pytest Suite

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y python3-tk
        apt-get install -y xvfb
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Pytest with xvfb
      run: xvfb-run -a pytest